### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by subnut** [Nova-Striker/mydotfiles#1]
Use [gruvbox-community/gruvbox](https://github.com/gruvbox-community/gruvbox) instead of morhertz/gruvbox
Use [subnut/vim-smoothie](https://github.com/subnut/vim-smoothie) till [this](https://github.com/psliwka/vim-smoothie/pull/21) PR is merged (See the linked issue in the PR for why I said to use my fork)

**Comment by Nova-Striker** [comment]
Okay. I will do that today
